# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stegosecrets < Formula
  desc "CLI for StegoSecretS. Encrypt and share secrets among trusted peers with AES-256, SSS and steganography."
  homepage "https://github.com/enrichman/stegosecrets"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/enrichman/stegosecrets/releases/download/v0.1.1/stegosecrets_0.1.1_Darwin_arm64.tar.gz"
      sha256 "43435d6fbcfeed67944eff5a92e14c0b84bf9dc7c7918865f53169748a61dd61"

      def install
        bin.install "stego"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/enrichman/stegosecrets/releases/download/v0.1.1/stegosecrets_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "7842be24f0a7d48d9a2cee4dc449b617c0730bf4a7739946c51aac0f0418aec1"

      def install
        bin.install "stego"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/enrichman/stegosecrets/releases/download/v0.1.1/stegosecrets_0.1.1_Linux_x86_64.tar.gz"
      sha256 "edc432434756f67c22e58e0e69cf17502697c0c12eec13e7783e23e45a9a9a14"

      def install
        bin.install "stego"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/enrichman/stegosecrets/releases/download/v0.1.1/stegosecrets_0.1.1_Linux_arm64.tar.gz"
      sha256 "e813df6e3345e65f36f96b12c493bef878e2634325797398388117d99182686f"

      def install
        bin.install "stego"
      end
    end
  end

  test do
    output = shell_output("#{bin}/stego version 2>&1")
    assert_match "stego version #{version}", output
    output = shell_output("#{bin}/stego decrypt 2>&1")
    assert_match "missing file to decrypt", output
  end
end
